spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 12345678


  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true

    hibernate:
      ddl-auto: create